### ISSUE TITLE
Невозможно спарсить новости

### ISSUE THREAD

**Issue by VegasChickiChicki** [verhovensky/news-api#1]
При попытке спарсить новости, третий пункт документации(вариант через докер), выдает ошибку:

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/app/news/management/commands/parse_news.py", line 24, in handle
    ozon = parse_news_links_ozon()
  File "/app/news/management/commands/yoparser.py", line 54, in parse_news_links_ozon
    driver = webdriver.Chrome(options=options, chrome_options=chrome_options)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by verhovensky** [comment]
Please verify news parsing working https://github.com/verhovensky/news-api/commit/0766428cdb20d7026550465c83ab30bb01cded4b

Try cloning branch parser_refactor and rerun it

**Comment by VegasChickiChicki** [comment]
@verhovensky К сожалению ваше решение мне не помогло, но помогла [эта](https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path) статья(в локальном режиме, без докера). 

Я просто заменил вызов драйвера на: 

`driver = webdriver.Chrome(ChromeDriverManager().install())`

**Comment by verhovensky** [comment]
@VegasChickiChicki 

1) Everything is parsed easily without docker. If you have chromedriver in your PATH variable, no extra libraries are needed.
This is a must and is written in docs of selenium package (which is installed and in requirements.txt of the current project).
Link to the official package documentation: https://pypi.org/project/selenium/
Btw I have already shown parsing process in local environment (not inside docker container) on the video screencast.

2) Conserning running parsing inside Docker container:
Did you delete all the containers and images and rebuild them again on the specified branch (parser_refactor)?


```
docker-compose down
docker image rm <images_names>
and only then:
docker compose up -d
```

3) webdriver-manager is a separate library. We do not need to install it as we are using Remote webdriver from a container with the hostname 'chrome'.
By using webdriver-manager we make our setup overcomplicated as it's main idea (as per library docs) is to "...simplify management of binary drivers for different browsers."

4) Would you please be so kind to provide your setup (environment).

5) I am certain about parsing (from docker) is working in the following environment (I also can provide a video screencast, if you mind it) ):


OS Info:
Linux 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux

Docker info:

Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.3
 Git commit:        100c70180f
 Built:             Sat Jun 11 23:27:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:

 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       a89b84221c
  Built:            Sat Jun 11 23:27:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false

 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6.m

 runc:
  Version:          1.1.3
  GitCommit:        

 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker Compose version 2.9.0

**Comment by VegasChickiChicki** [comment]
@verhovensky Увидел, что команда другая: `python manage.py parse_news docker`

При запуске выдает:

Using User-Agent: 
Mozilla/5.0 (Windows NT 5.1; rv:40.0) Gecko/20100101 Firefox/40.0 
usage: manage.py parse_news [-h] [--type TYPE] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color]
                            [--skip-checks]
manage.py parse_news: error: unrecognized arguments: docker

**Comment by verhovensky** [comment]
@VegasChickiChicki My bad, it was named argument (TYPE), so the commad would look:
```
python manage.py parse_news --type=docker
```
Please, respond if the issue was finally fixed.
Commit https://github.com/verhovensky/news-api/commit/e2c3531457058f6ffc5386c2c0c7f70c618bb17e

**Comment by VegasChickiChicki** [comment]
@verhovensky Все заработало, но пришлось внутри контейнера запустить миграции, почему то они не были сделаны скриптом.

**Comment by verhovensky** [comment]
@VegasChickiChicki 
Btw concerning migration - feel free to open another issue if you have problems running them.
Migrations are done normally if there is no cached images. I assume that you do have some cache / old images, db_data folder or volume.
You can verify that entrypoint.sh runs migration process just after database becomes available.

https://github.com/verhovensky/news-api/blob/main/djnews/entrypoint.sh#L7
